### ISSUE TITLE
Something wrong in the paper

### ISSUE THREAD

**Issue by SY-Xuan** [driptaRC/DECISION#1]
Thanks for your impressive work.
I think Eq. (3) in your paper is wrong.
As mentioned in your paper, you want to minimize the conditional entropy term and maximize the entropy of the empirical label distribution. So I think Eq. (3) should be formulated as follows:
<img src="https://latex.codecogs.com/gif.latex?\mathcal{L}_{IM}&space;=&space;\mathcal{L}_{ent}&space;-&space;\mathcal{L}_{div}" title="\mathcal{L}_{IM} = \mathcal{L}_{ent} - \mathcal{L}_{div}" />
By the way, the implementation of your code is the same as above.

**Comment by driptaRC** [comment]
We wish to _maximize_ the loss in Eq. 3. This is reflected in the optimization in Eq. 11, where we minimize the form you mention.

**Comment by SY-Xuan** [comment]
I don`t notice the maximize in the paper. You are right.
